import { Metadata } from "next";
import LoginForm from "@/components/Login/LoginForm";
 

export const metadata: Metadata = {
  title: 'Courses | login',
  description: 'Generated by create next app',
}
const LoginPage = () => {
   
  return (
    <LoginForm />
  );
};

export default LoginPage;